### ISSUE TITLE
error: call +[DemoClass _demoMethod] whit ObjC.classes.DemoClass._demoMethod();  

### ISSUE THREAD

**Issue by hnsxcxwpf2** [frida/frida-objc-bridge#20]
i want to call +[DemoClass _demoMethod] whit ObjC.classes.DemoClass._demoMethod();  
it will cash an error.    because the method name will be changed to :demoMethod. 
it happen in file index.js line: 1960
*****************
    function objcMethodName(name) {
        return name.replace(/_/g, ":");
    }
*****************

is here any way to avoid this ?

**Comment by oleavr** [comment]
Do it like this:

```JS
DemoClass['+ _demoMethod']();
```

**Comment by hnsxcxwpf2** [comment]
it works . thanks very much !!!!
