### ISSUE TITLE
I want to find some docs about mach-o 

### ISSUE THREAD

**Issue by hnsxcxwpf2** [frida/frida-objc-bridge#21]
HI, 
1. Mach-o file format layout and Mach-o file parsing and loading process 
2. objc syntax implementation mechanism

Where to find accurate information about the above topics?
There's an apple's official document, but it's a very old one. and None of the articles I found on Google are accurate.

**Comment by oleavr** [comment]
One good way is by reading Apple's open source code, when available. You can also learn a lot about Objective-C internals by reading the source code of the Swift compiler – it supports interop with Objective-C.

**Comment by hnsxcxwpf2** [comment]
Thanks
