### ISSUE TITLE
Hook variables in iOS app

### ISSUE THREAD

**Issue by ldgmart** [frida/frida-objc-bridge#3]
Hello, I'm trying to print or hook variables of the class but it is not working. 

Above is the a class definition of the app (class-dump file)
 
---------------------------------------------------------------------------
interface setInforViewController : UIViewController <NavigationBarViewDelegate, UITextFieldDelegate>
{
    UITextView *inforText;
    UITextField *currentEditingTextField;
    ...........   
     long long isTwoChk;  ----> target variable
    long long canUseId;   ----> target variable
    _Bool isrun;
}

---------------------------------------------------------------------------
As shown in Frida docs   "https://www.frida.re/docs/javascript-api/" ,
Here is the simple js source I wrote. 

if(ObjC.available) {
    for(var className in ObjC.classes) {
        if (ObjC.classes.hasOwnProperty(className)) {
         	if (className == "setInforViewController")  {
			send("Found our target class : " + className);
			var vars = ObjC.classes[nsclass].$ivars;  ---------> get variables of the class "setInfoViewController"
			var pro = eval('ObjC.classes.' + className + '.$protocols');
			var methods = eval('ObjC.classes.' + className + '.$ownMethods');
                        send("vars " + vars);                                      ---> print [Object Object]
			send("entry : " + JSON.stringify(vars));            --->print {}    ------> empty!!!
			send("pro : " + JSON.stringify(pro)); 
			send("methods:" + methods.length);
              }
      }
}
} 

--------------------------------------------------------------
Unlike $protocols and $ownMethods, $ivars does have empty value.

Is there another way to print or hook variables?

**Comment by oleavr** [comment]
Use `MemoryAccessMonitor` or `Stalker`.
