### ISSUE TITLE
ObjC.protocols is only enumerable at the first time

### ISSUE THREAD

**Issue by ChiChou** [frida/frida-objc-bridge#30]
Reproduce the bug:

* `frida -U [any app or target]`
* `[iPhone::WKWebView]-> ObjC.protocols` <-- the first time, it works
* `[iPhone::WKWebView]-> ObjC.protocols` <-- try again, it's empty(`{}`)

If you have the name of the protocol, the getter still works

**Comment by oleavr** [comment]
Whoah, what an embarrassing bug. Thanks for reporting it! ❤️
