### ISSUE TITLE
Hook ObjC closure

### ISSUE THREAD

**Issue by wrvenkat** [frida/frida-objc-bridge#9]
I'm trying to hook a closure provided for `LAContext`'s `evaluatePolicy:localizedReason:reply:` method. I have the following code where I create an ObjC block using arg[4] and passing a new block to the original method. In the new block, I'm trying to call the original block.

I'm making sure both the blocks live by putting them in an array. As you can see by the comments, one of them is working but the other call - the one from the new block gives me the following error.
```
Error: access violation accessing 0x0
    at input: 1
    at [anon] (repl1.js:37)
    at input: 1
```

Hooking code:
```
var blockArray = [];
var funcArray = [];

const evaluatePolicy_M = ObjC.classes.LAContext['- evaluatePolicy:localizedReason:reply:'];

Interceptor.attach(evaluatePolicy_M.implementation, {
   onEnter: function (args) {
		var laPolicy = args[2];
		var reason = ObjC.Object(args[3]);
		var replyBlockPtr = args[4];
		//create block from args[4]
		var origReplyBlock = new ObjC.Block(replyBlockPtr);
		blockArray.push(origReplyBlock);

		//create a new block
		var newReplyBlock = new ObjC.Block({
			retType: 'void',
			argTypes: ['int', 'pointer'],
			implementation: function (successOrFailure, nsError) {
				console.log("Success: "+successOrFailure+" nsError: "+ObjC.Object(nsError));
				console.log("blockArray[0].implementation: "+blockArray[0].implementation);
				//this is not working
				blockArray[0].implementation(1,null);
			}
		});
		blockArray.push(newReplyBlock);
		args[4] = newReplyBlock;
		
		//this is working
		//blockArray[0].implementation(1, null);
	}
});
```

**Comment by duonghung1269** [comment]
0x0 is value in hex not address, so it will thow that kind of error when you trying to use with ObjC.Object(0x0)

**Comment by candyhe33** [comment]
hi~ I‘m facing the same situation, wondering whether you solve this, thanks~

**Comment by oleavr** [comment]
This is definitely covered by one or more of the tools listed at https://github.com/dweinstein/awesome-frida – use `git grep` to find the code.

**Comment by profiling301** [comment]
> This is likely covered by one or more of the tools listed at https://github.com/dweinstein/awesome-frida – use `git grep` to find the code.





https://stackdev.space/questions/effective-ways-to-properly-designate-a-variable-inside-a-block
